name = "wayfinder"
version = "1.2.0"

description = "🧭 Typesafe Routing in Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "wayfinder" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
glance = ">= 3.0.0 and < 4.0.0"
tom = ">= 1.1.1 and < 2.0.0"
given = ">= 5.0.4 and < 6.0.0"
justin = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
